name: Build

on:
  push:
    branches: '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: src
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: zulu
        cache: gradle
    - name: Build with Gradle
      run: |
        cd src
        chmod +x ./gradlew
        ./gradlew build --no-daemon
        mkdir ../artifacts
        mv ./**/build/libs/*.jar ../artifacts
    - name: Upload mods as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts
